# RuboCop configuration file
# See https://docs.rubocop.org/rubocop/configuration.html for all options

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  Exclude:
    - 'db/schema.rb'
    - 'node_modules/**/*'
    - 'vendor/**/*'

Layout/LineLength:
  Max: 100

Metrics/MethodLength:
  Max: 10

Metrics/ClassLength:
  Max: 100

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/FrozenStringLiteralComment:
  Enabled: true

# Add or modify rules below as needed
